### ISSUE TITLE
[Bug] Not sure if this is an SBA issue or not

### ISSUE THREAD

**Issue by Absterge** [Fix3dll/SkyblockAddons#11]
### Bug Description

https://hst.sh/inavipexiz

### SBA Version

1.8.1

### Other Installed Mods

Mods can be seen in the crash log on the hastebin.

### Operating System

Windows 10

**Comment by Fix3dll** [comment]
Thank you for your reporting. Could you try with latest build again? You can reopen this thread in case the problem reoccurs.
