### ISSUE TITLE
[Bug] Dungeon Healing Circle Wall

### ISSUE THREAD

**Issue by Cats1337** [Fix3dll/SkyblockAddons#12]
### Bug Description

Setting 'Show Dungeon Healing Circle Wall' Healing Circle Opacity to lower than the default 0.40 resets the value upon reloading the game. Keep having to reset it after setting it to 0.20.

### SBA Version

1.8.2

### Other Installed Mods

Autotip 3.0
Better Chat 1.5
BLock Overlay 4.0.3
Chatting 1.4.1
ChatTriggers 2.2.0-1.8.9
Cowlection 1.8.9-0.16.0
CrashPatch 1.4.0
Custom Main Menu 2.0
Cravy's Reward Claim 1.0.5
Holdlook 1.2 (Custom Mod, source code on my GitHub)
Hypixel Autocomplete 
Hytils Reborn 1.5.0
Mouse Tweaks 2.6.2
NEU 2.1.1+Alpha-19.8be4648
Optibye 1.0.0
Patcher 1.8.7
Optifine M6_pre2
Report PLus 1.0.0
Scrollable Tooltips
SimpleToggleSprint 2.2.0
SkyblockAddons 1.8.2+84
Skyclient Updater 1.3.2
SkyHanni 0.19
Skytils 1.7.4
SoopyV2Forge 1.1
Synthesis 0.3.1
VanillaHUD 1.1.1
```

### Operating System

Atlas Windows 10 22H2

### Crash Report

_No response_

**Comment by Fix3dll** [comment]
@Cats1337 thanks for your feedback. I hope your problem is solved. If your problem is not solved, you can reopen issue again.
