### ISSUE TITLE
Health Number/Bar bugs out in Rift

### ISSUE THREAD

**Issue by Tetro48** [Fix3dll/SkyblockAddons#13]
### Bug Description

Steps to replicate:
- Have either Health Bar and/or Health Number enabled.
- Enter the Rift

Expected behavior:
- 7.5/10 hearts: 15/20
- 15/15 hearts: 30/30

Actual behavior:
- 15/15 hearts: 3,178/30 (3,178 representing max HP outside of the Rift)

### SBA Version

1.8.2

### Other Installed Mods

```md
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9.jar (11.15.1.2318)]
[Essential][Essential (forge_1.8.9).jar (13437+deploy-staging+gd2fc09762)]
[OneConfig][OneConfig (1.8.9-forge).jar (0.2.0-alpha180)]
[Chatting][Chatting-1.4.2-beta5.jar (1.4.2-beta5)]
[ChatTriggers][ctjs-2.2.0-1.8.9.jar (2.2.0-1.8.9)]
[Damage Tilt][DamageTilt-1.8.9-0.2.0-clientonly.jar (1.8.9-0.2.0-clientonly)]
[ExtendPolyphonyLimit][ExtendPolyphonyLimit-1.3-for1.8-1.12.2.jar (1.3-for1.8-1.12.2)]
[FoamFix][foamfix-0.6.3-law-1.8.x.jar (@VERSION@)]
[Danker's Skyblock Mod][MC.1.8.9.Danker.s.Skyblock.Mod.-.2.1.jar (2.1)]
[NotEnoughUpdates][NotEnoughUpdates-2.1.1+ci.4603182-dep.jar (2.1.1+ci.4603182)]
[Patcher][Patcher-1.8.7 (1.8.9).jar (1.8.7)]
[Scrollable Tooltips][Scrollable Tooltips-1.4 (1.8.9).jar (LOCAL)]
[SkyblockAddons][SkyblockAddons-1.8.2+84-for-MC-1.8.9.jar (1.8.2+84)]
[SkyHanni][SkyHanni-0.19.jar (0.19)]
[SoopyV2Forge][soopyv2forge-1.1.jar (1.1)]
[Backported Subtitles][Sound Subtitles-1.2.2 (1.8.9).jar (1.2.2)]
```
### Operating System

Windows 10

**Comment by Tetro48** [comment]
![image](https://github.com/Fix3dll/SkyblockAddons/assets/76738929/9ec8dcfc-caac-4c10-ab61-8af9e873e665)

**Comment by Fix3dll** [comment]
@Tetro48 Could you send full screenshot (with scoreboard)  please? And type `/locraw` if possible while before taking screenshot.

**Comment by Tetro48** [comment]
![image](https://github.com/Fix3dll/SkyblockAddons/assets/76738929/9c6de78e-2df0-48cf-8df9-84e0506b6730)

**Comment by Fix3dll** [comment]
@Tetro48 Can you try again with the latest build? Most likely the problem was due to unicode.

**Comment by Fix3dll** [comment]
@Tetro48 thanks for your feedback. I hope your problem is solved with latest build artifacts. If your problem is not solved, you can reopen issue again.
