### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Falsus2** [Fix3dll/SkyblockAddons#14]
### Bug Description

The enchantment transylvanian doesn't work with parse enchant tooltuips

### SBA Version

1.8.2

### Operating System

Windows 10

**Comment by Falsus2** [comment]
![image](https://github.com/Fix3dll/SkyblockAddons/assets/45407472/bd409bcc-5906-4f8a-8efc-bfe633feb1ab)

**Comment by Fix3dll** [comment]
@Falsus2 thanks for your report. Please update your version with latest build.
