### ISSUE TITLE
[Bug] Skill Progress Bar is not visible

### ISSUE THREAD

**Issue by CubedTemp** [Fix3dll/SkyblockAddons#18]
### Bug Description

Skill Progress Bar is not working (not visible)

### SBA Version

1.8.5+152

### Other Installed Mods

![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/3c302047-4b3a-452d-a2b3-9dd8f8ce3e52)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/f3ea89e3-1778-4741-af22-11fd6f8a6946)

### Operating System

Windows 11

**Comment by CubedTemp** [comment]
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/f9898e3d-7732-41f8-abeb-eee6186f0d5c)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/20411ce9-7ded-47cc-804f-72017d0511d3)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/02630207-bb3e-4fcf-bdaf-4ac10c909897)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/090fd650-aad0-4858-bd42-394604e7ca8a)

**Comment by Fix3dll** [comment]
@CubedTemp It should be fixed with the latest version. Thanks for your reporting.

**Comment by CubedTemp** [comment]
Fixed as of SBA 1.8.5+154.
