### ISSUE TITLE
[Bug] Crimsion Isle touching other islands when hovered (INCONSISTENT)

### ISSUE THREAD

**Issue by CubedTemp** [Fix3dll/SkyblockAddons#19]
### Bug Description

When hovered, the Crimsion Isle touches the End and the Deep Caverns, unlike the other islands (excl. The End)
When the End is hovered, it touches the Crimsion Isle.

Possibly decrease the size of the Crimsion Isle OR decrease the zoom when hovered.

### SBA Version

1.8.5+152

### Other Installed Mods

![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/1079440a-560e-4ab2-87e3-3d8e993e91ab)
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/396472c3-9fac-43f4-96e1-9cbcb57be7ef)

### Operating System

Windows 11

**Comment by CubedTemp** [comment]
Crimson Isle Hovered:
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/cde803a2-8394-4106-858a-0f5205ea7616)

The End Hovered:
![image](https://github.com/Fix3dll/SkyblockAddons/assets/89503528/7899ccb7-0520-4040-97aa-51cfc590c8d9)

**Comment by Fix3dll** [comment]
Its minor visual bug. I will fix it in next versions.

**Comment by CubedTemp** [comment]
Will keep issue open until fixed.
