### ISSUE TITLE
Chroma Enchants stopped working with Version 1.8.8+224

### ISSUE THREAD

**Issue by Iceshadow1404** [Fix3dll/SkyblockAddons#27]
### Bug Description

After updating from version 1.8.7+193 to 1.8.8+224 chroma Enchants stopped showing and they are grey now. 

![grafik](https://github.com/Fix3dll/SkyblockAddons/assets/50039154/cf3fcf81-6210-4c53-9307-b7e7bbadb7d6)

### SBA Version

1.8.8+224

### Other Installed Mods

Only SBA 

### Operating System

Windows 11

**Comment by Fix3dll** [comment]
@Iceshadow1404 Oopsie. Thanks for your reporting.
