### ISSUE TITLE
[Bug] Conflict with NEU

### ISSUE THREAD

**Issue by Falsus2** [Fix3dll/SkyblockAddons#28]
### Bug Description

Improved SB Menus has the wrong text color when used with the latest SBA update. If you remove the mod or use an older version, it reverts back to normal.

### SBA Version

1.8.9+227

### Other Installed Mods

NEU v2.1.1-Pre-5

### Operating System

Windows 10

**Comment by Falsus2** [comment]
How it looks now:
![image](https://github.com/Fix3dll/SkyblockAddons/assets/45407472/20addf21-c702-4e43-a40b-89ca5c6e1550)
How it should look / without SBA:
![image](https://github.com/Fix3dll/SkyblockAddons/assets/45407472/5c2c8cef-6a39-4586-999e-8e29703a7871)

**Comment by Fix3dll** [comment]
@Falsus2 oopsie. Thanks for reporting.

**Comment by Falsus2** [comment]
The issue is reintroduced with beta 5. Same bug as reported before

**Comment by Fix3dll** [comment]
@Falsus2 thanks for reporting.
