### ISSUE TITLE
[Bug] No fancy warp for the new Dwarven Base Camp teleport

### ISSUE THREAD

**Issue by ddabble** [Fix3dll/SkyblockAddons#32]
### Bug Description

The command is `/warp basecamp`, or any of the other ones listed at the bottom of [the Travel Scrolls wiki article](https://wiki.hypixel.net/Travel_Scrolls#Fast_Travel_List).

### SBA Version

1.9.0-beta.1+232

### Operating System

Windows 11

**Comment by Fix3dll** [comment]
@ddabble I forgot to add this to beta.2. I will add it in the next version.
