### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by The-Deerman** [Fix3dll/SkyblockAddons#34]
### Bug Description

Every mob, player, and npc (except Jerry's) gets highlighted, only inside skyblock, only happens when skyhanni is being used, still happens with all features disabled in /sba
![2024-04-21_14 44 01](https://github.com/Fix3dll/SkyblockAddons/assets/113066400/9332eb66-8194-4db6-95a7-e3ad3d41b101)
This didn't happen on sba 1.8.7+177

### SBA Version

1.8.9+227 and 1.9.0-beta.2+242

### Other Installed Mods

```md
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar (11.15.1.2318)]
[Essential][Essential (forge_1.8.9).processed.jar (1.3.1.3+g88238d7752)]
[Skytils][BSMod-1.9.2.jar (1.9.2)]
[NotEnoughUpdates][NotEnoughUpdates-2.1.1-Alpha-27.jar (2.1.1+Alpha-27.e55bf40)]
[Patcher][Patcher-1.8.7 (1.8.9).jar (1.8.7)]
[SkyblockAddons Unofficial][SkyblockAddons-1.9.0-beta.2+242-for-MC-1.8.9.jar (1.9.0-beta.2+242)]
[SkyHanni][SkyHanni-0.25.Beta.10.jar (0.25.Beta.10)]
[spark][spark-forge189-bde4ce2ff-mod.jar (${pluginVersion})]
```

### Operating System

Windows 10

### Crash Report

-

**Comment by The-Deerman** [comment]
This bug happens when Skyhanni Highlight Party Members is enabled

**Comment by Triggered0** [comment]
i have the same issue

**Comment by Fix3dll** [comment]
@The-Deerman @Triggered0 Could you try with latest build? I would be happy if you feedback.

**Comment by Triggered0** [comment]
@Fix3dll its fixed thx
