### ISSUE TITLE
[Bug] Game doesn't launch following build #247 (Incompatibility with CrashPatch)

### ISSUE THREAD

**Issue by Falsus2** [Fix3dll/SkyblockAddons#37]
### Bug Description

After updating to the newest build, the game does not launch and throws Exit Code: 1. Any versions at or above build #247 experiences this problem on launch. After looking into it, the problem originates from an incompatibility with CrashPatch brought about by new builds.

### SBA Version

1.9.0-beta.3

### Other Installed Mods

CrashPatch-1.8.9-forge-2.0.0

### Operating System

Windows 10

**Comment by Fix3dll** [comment]
@Falsus2 please open ticket on their discord: https://polyfrost.org/discord/

**Comment by Fix3dll** [comment]
@Falsus2 should be resolved with 1.9.0-beta.5. If not you can reopen. Thanks for reporting.
