### ISSUE TITLE
[Suggestion] Add support for Hypixel Skyblock remakes

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Fix3dll/SkyblockAddons#4]
### Bug Description

Though this is NOT a bug report, I found no other option in the "issues" page. Either way; I want this SBA fork to have support for Hypixel Skyblock remakes, eg: StormAlpha, and Skysim.

### SBA Version

1.8.0-beta.1

### Operating System

Windows 11

**Comment by Fix3dll** [comment]
@gabrielvicenteYT you should read hypixel forum thread: https://hypixel.net/threads/5362745/
I think you are talking about other servers. First of all, this mod is designed and created for Hypixel Skyblock players. Second, the purpose of this fork is to update existing features to run on the current server version and, if possible, add QoL features that are not too costly to add. Thank you for your interest.

**Comment by gabrielvicenteYT** [comment]
@Fix3dll Should I try to add compat for SkySim and StormAlpha?
