### ISSUE TITLE
[Bug] Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION.

### ISSUE THREAD

**Issue by InnocentHumanNiko** [Fix3dll/SkyblockAddons#42]
### Bug Description

I have no idea how this happened but it started after i update skyhanni, i tried using the official and non official and none works.

### SBA Version

1.9.0 beta 9

### Other Installed Mods

apec 1.11.6
Chatting 1.5.3
ctjs 2.2.0
dulkirmod 1.2.8
dungeon rooms 3.4.1
neu 2.2.2
optifine m5
patcher 1.8.9
scrollable tooltips 1.4
sba 1.9.0 beta 9
skyhanni 0.25
skytils 1.9.7
waveycapes 1.2.0

### Operating System

Windows 11

### Crash Report

[latest.log](https://github.com/Fix3dll/SkyblockAddons/files/15447200/latest.log)

**Comment by Fix3dll** [comment]
@InnocentHumanNiko Backup your `.minecraft/config/skyblockaddons_persistent.cfg` then remove it and restart the game. Probably your cfg file is broken.

**Comment by InnocentHumanNiko** [comment]
Somehow, my config file is empty and when I deleted it, it works now. Thanks!
