### ISSUE TITLE
Game crashing when you try to salvage items in dungeon hub

### ISSUE THREAD

**Issue by Visiuss** [Fix3dll/SkyblockAddons#44]
### Bug Description

You enter dungeon hub, open black smith click on salvage items and game crashes.

### SBA Version

SkyblockAddons-1.9.0-beta.11

### Other Installed Mods

![image](https://github.com/Fix3dll/SkyblockAddons/assets/172290326/34233e35-66b6-4ce2-93b4-5b92b5997605)

### Operating System

Windows 11

### Crash Report

[crash-2024-06-10_16.06.30-client.txt](https://github.com/user-attachments/files/15775412/crash-2024-06-10_16.06.30-client.txt)

**Comment by Fix3dll** [comment]
Thanks for report. Probably your essence widget closed or its not appear because your tab list is too full. I will fix this crash on next beta version.
