### ISSUE TITLE
[Bug] Rainbow/Chroma Enchant Colors Appearing as Boldfaced Gold

### ISSUE THREAD

**Issue by falsetf** [Fix3dll/SkyblockAddons#49]
### Bug Description

Upon switching to this unofficial fork of SBA, I've noticed that the rainbow enchants to show max-level enchants have turned into boldfaced gold colors. 

When I use my old official version of SBA (SkyblockAddons-1.7.3+7380-for-MC-1.8.9), rainbow enchant colors appear as normal. However, upon swapping the mod to the most recent unofficial version (SkyblockAddons-1.9.0-beta.12), or a slightly outdated version (SkyblockAddons-1.9.0-beta.11.1), the rainbow enchants are boldfaced gold.

I have tried editing pretty much every option available in the submenus of Parse Enchant Tooltips in SBA to attempt to fix this issue, but none have solved it (in fact, nothing seems to have an effect on anything). I have also generated a new config file, as per a suggestion on a somewhat similar bug report, but that did not solve it either.
## Old SBA
![image](https://github.com/Fix3dll/SkyblockAddons/assets/78240009/bdbbef57-d7de-461f-9c81-18d2ad2d81cf)
## New SBA
![image](https://github.com/Fix3dll/SkyblockAddons/assets/78240009/c5837564-88e0-40bd-9aad-ad303a8ad801)
## Exception
The exception to this is in the NEU item menu where the rainbow colors show as normal with the unofficial version:
![image](https://github.com/Fix3dll/SkyblockAddons/assets/78240009/56eedf42-517f-40c5-a609-2538f2b93275)
Other exceptions include inside of NEU's profile viewer, where the rainbow enchants show up as intended. 

I love the new changes you have made to the mod, and appreciate the effort you're putting in to continue the development of this mod. Thanks in advance.  

### SBA Version

1.9.0-beta.12

### Other Installed Mods

```md
# System Stats
[OS][Windows 10]
[CPU][20x 12th Gen Intel(R) Core(TM) i7-12800H]
[Display][1920x1080 (NVIDIA Corporation)]
[GPU][NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2]
[GPU Driver][4.6.0 NVIDIA 555.99]
[Maximum Memory][16067MB]
[Shaders][TRUE]
# Java Stats
[Java][1.8.0_51 64bit]
[Memory][ 43% 1761/4096MB]
[Memory Allocated][ 51% 2112MB]
# Game Stats
[FPS][129]
[Loaded Mods][34]
[Forge][11.15.1.2318]
[Optifine][TRUE]
# Neu Settings
[On SkyBlock][TRUE]
[Mod Version][2.3.0+32ee0a75]
[Version Id][20300]
[SB Profile][Pineapple]
# Repo Stats
[Last Commit][89f7c81f9dd960d3a46f7caa6d90a76bb6d69a23]
[Repo Location][https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/tree/master]
[Using Backup][false]
[Loaded Items][6490]
[Lowest Bin API Location][moulberry.codes]
# Repo Files
[.gitattributes]
[.github][1]
[.gitignore]
[.vscode][2]
[constants][31]
[enforced_values][2]
[items][6490]
[LICENSE]
[mobs][220]
[neu-items-master.zip]
[README.md]
[update.json]
[update.json.asc]
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9.jar (11.15.1.2318)]
[Essential][Essential (forge_1.8.9).processed.jar (1.3.2.7+g7245995b31)]
[OneConfig][OneConfig (1.8.9-forge).jar (0.2.2-alpha212)]
[BazaarNotifier][BazaarNotifier-1.7.2.jar (1.7.2)]
[Chatting][Chatting-1.8.9-forge-2.0.4.jar (2.0.4)]
[CrashPatch][CrashPatch-1.8.9-forge-2.0.1.jar (2.0.1)]
[ChatTriggers][ctjs-2.2.0-1.8.9.jar (2.2.0-1.8.9)]
[Dungeon Rooms Mod][Dungeon_Rooms-3.4.1.jar (3.4.1)]
[FPS Reducer][FpsReducer-mc1.8.9-1.10.3.jar (mc1.8.9-1.10.3)]
[Hypixel Autocomplete Mod][Hypixel Autocomplete-1.1 (1.8.9).jar (LOCAL)]
[Hytils Reborn][Hytils Reborn-1.8.9-forge-1.7.1.jar (1.7.1)]
[Danker's Skyblock Mod][MC.1.8.9.Danker.s.Skyblock.Mod.-.2.2.jar (2.2)]
[NotEnoughUpdates][NotEnoughUpdates-2.3.0.jar (2.3.0+32ee0a75)]
[Odin][Odin-1.2.5.beta7.jar (1.2.5.beta7)]
[Optibye][Optibye-1.0.0-dep.jar (1.0.0)]
[OverflowAnimations][OverflowAnimations-1.8.9-forge-2.2.2.jar (2.2.2)]
[PolyCrosshair][PolyCrosshair-1.8.9-forge-1.0.2.jar (1.0.2)]
[PolyNametag][PolyNametag-1.8.9-forge-1.0.6.jar (1.0.6)]
[Patcher][PolyPatcher-1.8.9-forge-1.9.2.jar (1.9.2)]
[PolySprint][PolySprint-1.8.9-forge-1.0.1.jar (1.0.1)]
[Report Plus][ReportPlus-1.0.2.jar (1.0.2)]
[Gravy's Reward Claim][RewardClaim-1.0.6.jar (1.0.6)]
[Scrollable Tooltips][Scrollable Tooltips-1.4 (1.8.9).jar (LOCAL)]
[SkyblockAddons][SkyblockAddons-1.7.3+7380-for-MC-1.8.9.jar (1.7.3+7380)]
[SkyblockExtras][SkyblockExtras-2.2.0-pre20-RELEASE.jar (2.2.0-pre20)]
[SkyClient Updater][SkyClient-Updater-1.8.9-forge-1.3.7.jar (1.3.7)]
[SkyClientCosmetics][SkyClientCosmetics-1.8.9-forge-1.1.16.jar (1.1.16)]
[SkyHanni][SkyHanni-0.25.jar (0.25)]
[Skytils][Skytils-1.10.0-pre9 (fixed).jar (1.10.0-pre9)]
[Smooth Scrolling Everywhere][smooth-scrolling-everywhere-1.2.jar (1.2)]
[SoopyV2Forge][soopyv2forge-1.1.jar (1.1)]
[SomeWaterSolver][WaterSolver.jar (unspecified)]
```

### Operating System

Windows 11

**Comment by Fix3dll** [comment]
@falsetf did you check skyhanni enchant color?

**Comment by falsetf** [comment]
Thank you for the very quick response, I was unaware that SkyHanni had an enchant parsing feature. That solved it. Thank you.
