### ISSUE TITLE
[Bug] Mana ActionBar Item shows in Mining Islands despite Custom Mana Display enabled 

### ISSUE THREAD

**Issue by soultwistrune** [Fix3dll/SkyblockAddons#6]
### Bug Description

 Mana Action Bar Item shows in Mining Islands despite Custom Mana Display enabled. Like the numbers will show on the actionbar, even if the Mana Text/Mana Bar is enabled.

### SBA Version

1.8.0-beta.1

### Other Installed Mods

Optifine M5
NEU
Skytils
Skyhanni

### Operating System

macOS Sonoma Developer Beta

**Comment by Fix3dll** [comment]
@soultwistrune Can you try updating the mod first?

**Comment by soultwistrune** [comment]
> @soultwistrune Can you try updating the mod first?

I'm on the latest version (1.8.1 Build 64)

**Comment by Fix3dll** [comment]
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/fad5713b-93b7-4033-b7f3-072ddfd7f6cb)
I couldn't understand your problem. Can you explain in more detail?

**Comment by soultwistrune** [comment]
<img width="434" alt="Screenshot 2023-08-14 at 9 51 43 AM" src="https://github.com/Fix3dll/SkyblockAddons/assets/114491687/a4f05251-7ba3-4993-a421-4984ef5e2d3d">
something like this

**Comment by Fix3dll** [comment]
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/50a58b5e-0e89-4361-8f72-9792ff7cc176)
There is no problem on my client. It could be releated to resource packs or other mods?

**Comment by Fix3dll** [comment]
![image](https://github.com/Fix3dll/SkyblockAddons/assets/10743391/6254c66c-e364-4ddf-8124-5ca5575a6050)
@soultwistrune I need more information. I also tried close to your GUI settings and with resource packs. The problem may be caused by other mods.

**Comment by soultwistrune** [comment]
Probably
