### ISSUE TITLE
Fancy warp menu doesn't have carnival warp

### ISSUE THREAD

**Issue by TomekoYT** [Fix3dll/SkyblockAddons#62]
### Bug Description

Add /warp carnival to the fancy warp menu

### SBA Version

1.9.0-beta16

### Operating System

Windows 10

**Comment by Fix3dll** [comment]
@TomekoYT completed with https://github.com/Fix3dll/SkyblockAddons/commit/22011ae334d2097b5d4e0d9389d050281ced2c66
