### ISSUE TITLE
[Bug] Game crashes after entering into skyblock

### ISSUE THREAD

**Issue by galaxysavitar** [Fix3dll/SkyblockAddons#73]
### Bug Description

Whenever I try to get into hypixel skyblock, the server is loaded for a second and then becomes stuck. No sound is outputted and the screen is stuck like the screenshot attached. I tried launching it again but still it occurs
![{D67508A3-F5B2-4736-A3DA-242C793C62D8}](https://github.com/user-attachments/assets/e41a458c-037f-4a1c-bbcc-dc9e9dc17066)

### SBA Version

1.9.0-beta.20

### Other Installed Mods

1.8.9.SkyblockPersonalized.1.7.0.0
Chatting [2.0.6]
CrashPatch (https://github.com/Polyfrost/CrashPatch) [2.0.1]
Danker's Skyblock Mod (https://github.com/bowser0000/SkyblockMod) [2.3.1]
Dungeon Rooms Mod (https://discord.gg/7B5RbsArYK) [3.4.1]
Essential Mod (https://modrinth.com/mod/k2ZPuTBm) [BfiYnyNE]
Gravy's Reward Claim [1.0.6]
Hypixel Autocomplete Mod [LOCAL]
Hytils Reborn (https://github.com/Polyfrost/Hytils-Reborn) [1.7.3]
ItemPhysic (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076336) [1.3]
Mixmetica (https://modrinth.com/mod/mixmetica) [2.1.1]
NotEnoughUpdates (1.8.9) (https://modrinth.com/mod/GGamhqbw) [2.4.0+c47010a4]
Optibye [1.0.0]
OverflowAnimations [2.2.5]
Partly Sane Skies (https://modrinth.com/mod/jlWHBQtc) [beta-v0.6.2-prerelease-8]
Patcher (https://modrinth.com/mod/YknNc5nN) [1.10.1]
PolyNametag [1.0.7]
PolySprint (https://github.com/Polyfrost/PolySprint) [1.0.1]
QuickQuit (https://modrinth.com/mod/uhBpdFWZ) [1.0.1]
Raw Input (https://github.com/xCuri0/RawInputMod) [1.1.5]
Scrollable Tooltips [LOCAL]
SkyClient Updater (https://modrinth.com/mod/4JT4oKKX) [1.3.11]
SkyClientCosmetics (https://modrinth.com/mod/Wlq56PJK) [1.2.2]
SkyHanni (https://modrinth.com/mod/byNkmv5G) [0.27]
SkyblockAddons Unofficial (https://modrinth.com/mod/F35D4vTL) [1.9.0-beta.20+399]
Skytils (https://github.com/Skytils/SkytilsMod) [1.10.7]
Smooth Scrolling Everywhere (https://github.com/shedaniel/SmoothScrollingEverywhere) [1.2]
VanillaHUD [2.2.10]
Velox Caelo [1.0.2]
preview_OptiFine_1.8.9_HD_U_M6_pre2
redirectionor-1.4 for 1.12.2-1.8.8

### Operating System

Windows 11

**Comment by galaxysavitar** [comment]
This only occurred after I updated to SBA beta 20 btw

**Comment by Fix3dll** [comment]
@galaxysavitar Could you share crash log? Did you try remove all mods except SBA? If its work while just SBA exist could you try to add other mods one by one and find conflict mod?

**Comment by twenSG** [comment]
Same, crashed after the update, no issues with the previous release

**Comment by Fix3dll** [comment]
Its related with VanillaHUD. VanillaHUD needs update.
https://github.com/Polyfrost/VanillaHUD/blob/d125c3dab4e8cecf926493e0ea62ce611d4cc5dc/src/main/java/org/polyfrost/vanillahud/VanillaHUD.java#L341
You can downgrade SBA or uninstall VanillaHUD until it is updated.
