### ISSUE TITLE
[Enhancement] Make Jerry's Workshop visible throughout whole Hypixel's winter season in fancy warp menu

### ISSUE THREAD

**Issue by TomekoYT** [Fix3dll/SkyblockAddons#79]
### Bug Description

Jerry's Workshop is open throughout whole Hypixel's winter season but fancy warp menu shows it only at regular time (the end of the skyblock year)

### SBA Version

1.9.1

### Operating System

Windows 10

**Comment by Fix3dll** [comment]
@TomekoYT thanks for sharing this with us. Now you can test this with latest build artifact.
