### ISSUE TITLE
[enhancement] Volume slider (or follow minecraft volume) for Bal notifier

### ISSUE THREAD

**Issue by 7Kav** [Fix3dll/SkyblockAddons#80]
### Bug Description

Title: Bal notifier is extremely loud even with my volume down. if possible is there any way to make the volume controllable (or just turned down regularly)

### SBA Version

1.9.2 (release)

### Other Installed Mods

BehindYouV3
ChatTriggers
Controlling
EntityCulling
Fancy Warp Menu
Fullscreen Windowed
Hot Shirtless Men
IdleTweaks
NotEnoughUpdates (1.8.9)
Optibye
OverflowAnimations
Partly Sane Skies
Patcher
Polished GUI
Scatha-Pro
SkyClient Updater
SkyGuide
SkyHanni
Skyblock Features
SkyblockAddons Unofficial
SkyblockExtras
Skytils
Titanium
Velox Caelo
VolcAddons-1.0
preview_OptiFine_1.8.9_HD_U_M6_pre2

### Operating System

Windows 11

**Comment by Fix3dll** [comment]
@7Kav You can now adjust the volume using the Players setting in the sound settings. You can test with latest build artifact. Thanks for report.
