### ISSUE TITLE
[Crash] Crash with LabyMod

### ISSUE THREAD

**Issue by flikamasha89** [Fix3dll/SkyblockAddons#81]
### Bug Description

When using LabyMod the Unofficial Skyblock Addons is causing a crash. I did test going back to version 1.8.7

### SBA Version

1.8.8+

### Operating System

Windows 11

### Crash Report

Two crash reports get generated. Here are both of them.

https://pastebin.com/G4Ed3X1Y
https://pastebin.com/imFJ9UNE

**Comment by Fix3dll** [comment]
@flikamasha89 LabyMod is not supported. LabyMod have own custom fork of SkyblockAddons.
